### DISCUSSION TITLE
followup from "Faker-ruby has too many generators to maintain" faker-ruby/faker#2689

### DISCUSSION THREAD

**Discussion by stoivo** [psibi/fakedata#50] [General]
Hi, I want to ask a few questions related to you comment, https://github.com/faker-ruby/faker/issues/2689#issuecomment-1448433677.  Since faker uses I18n it supports translations with fallback to english I think? how to you know which yaml files you have to parse? since you only parse yaml files on demand?

**Comment by psibi** [comment]
For fakedata, you pass the `locale` explicitly. By default, it uses english. You can chose to use any other local explicitly, if you opt to it.

> how to you know which yaml files you have to parse? since you only parse yaml files on demand?

Since we know the locale and the yaml files, based on the usage - you can parse the appropriate yaml file and maintain the cache of the parsed yaml file. So throughout the run of the program, you don't have to read the same yaml file again.

**Comment by stoivo** [comment]
I assume you use the filename to guess the scope of the file. So  the file containting this yaml should be called valleyball.yml. I did some sampels and it seems to be done like this all the time. I don't think this is required for the current solution faker uses. I think I18n don't care  file name.
```yaml
en:
  faker:
    volleyball:
      team:
      - A.S.D. Pallavolo Torino
      - ACH Volley Ljubljana
      - ADC Pirelli
      - AERO Odolena Voda
```
